using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Bluecap.Lib.Utils
{
    public static class RandomUtils
    {
        // Function to return the next random number
        static int GetNum(ArrayList v)
        {

            // Size of the vector
            int n = v.Count;

            Random rand = new Random();

            // Make sure the number is within
            // the index range
            int index = (rand.Next() % n);

            // Get random number from the vector
            int num = (int)v[index];

            // Remove the number from the vector
            v[index] = (int)v[n - 1];
            v.Remove(v[n - 1]);

            // Return the removed number
            return num;
        }

        // Function to generate n
        // non-repeating random numbers
        public static IEnumerable<int> GenerateRandomPermutation(int n)
        {
            ArrayList v = new ArrayList(n);
            IEnumerable<int> permutation = new List<int>();
            // Fill the vector with the values
            // 0, 1, 2, ..., n - 1
            for (int i = 0; i < n; i++)
                v.Add(i);

            // While vector has elements get a
            // random number from the vector
            // and print it
            while (v.Count > 0)
            {
                //Console.Write(getNum(v) + " ");
                permutation = permutation.Append(GetNum(v));
            }
            return permutation;
        }
    }

    // This derived class converts the uniformly distributed random
    // numbers generated by base.Sample() to another distribution.
    public class RandomProportional : Random
    {
        // The Sample method generates a distribution proportional to the value
        // of the random numbers, in the range [0.0, 1.0].
        protected override double Sample()
        {
            return Math.Sqrt(base.Sample());
        }

        public override int Next()
        {
            return (int)(Sample() * int.MaxValue);
        }
    }
}
